# Generated by Django 5.0.10 on 2025-01-01 17:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('DataID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('CreateID', models.CharField(max_length=30)),
                ('CreateDate', models.DateTimeField()),
                ('UpdateID', models.CharField(max_length=30)),
                ('UpdateDate', models.DateTimeField()),
                ('DataFlag', models.BinaryField(max_length='max')),
                ('UserID', models.CharField(max_length=20)),
                ('UserName', models.CharField(max_length=100)),
                ('Password', models.TextField()),
            ],
        ),
    ]
